### PR TITLE
bump version of deconz package

### PR DESCRIPTION
**Pull request by maxhbr**

### CODE REVIEW

**Comment by bjornfor** [comment]
Funny timing, I just did the same change myself _yesterday_!

I just pushed my changes now: 07297d2f10344480e5e02788fcf539c5046ecd88, 6dd26b1e344ace4703c8c81a1c818da5f9cba5d7.

Perhaps it's time to move this to nixpkgs?

**Comment by bjornfor** [comment]
Closing since the change has been integrated, but I'd still like to hear your thoughts on adding it to nixpkgs.

Does deconz work well for you?

**Comment by maxhbr** [comment]
> Closing since the change has been integrated, but I'd still like to hear your thoughts on adding it to nixpkgs.

I would like to see it in nixpkgs.

> Does deconz work well for you?

The server runs (on port 80, with your service config) but none of my sensors was yet able to establish a connection.

**Comment by bjornfor** [comment]
> but none of my sensors was yet able to establish a connection.

Hm, that part worked well in my case. I have the ConBee II and several Aqara/Xiaomi sensors (temprature/humidity/pressure). The sensors were added in the webapp (Phoscon) without problems. 

I just have problems with auth / password, which makes me not trust it. Sometimes I cannot login and I have to reset the service and load the config from backup.

**Comment by maxhbr** [comment]
I have the same hardware here. But probably the firmware of the ConBee is outdated or the sensors were already paired with another instance.

**Comment by bjornfor** [comment]
I didn't try the firmware update yet, but for the sensors just press the button for >= 5 seconds after having set the Phoscon app to "add new sensor".

**Comment by maxhbr** [comment]
I am confused by the `Firmware: not connected` entry:


But I have not yet started to debug it.

**Comment by bjornfor** [comment]
Don't know if I've seen that before. In my system there is a series of hex digits where you have "Not connected".

**Comment by maxhbr** [comment]
Firmware update works with:
```
sudo /nix/store/hy...rn-deconz-2.05.77/bin/GCFFlasher_internal -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x26580700.bin.GCF
```

EDIT: fixed the UI Problem.
EDIT: But still the sensors are not registered. I need to debug that

**Comment by bjornfor** [comment]
@maxhbr: FYI, I created a proper deconz module: d9a7456e5b21e94dd38baeb88c627b9e0492643a.

**Pull request closed without merging**
